server:
  port: 8089

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${PROD_KEYCLOAK_HOST}/realms/master2
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect3333333333333333333333333333333333333333333333333333333333/certs

  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

#  main:
#    allow-circular-references: true

jwt:
  auth:
    converter:
      resource-id: t_client
      principle-attribute: preferred_username



#logging:
#  file:
#    path: .
#    name: my_log.txt
