server:
  port: 8089

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master2
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:5432/towersly_app
    username: postgres
    password: postgre

#  main:
#    allow-circular-references: true

jwt:
  auth:
    converter:
      resource-id: t_client
      principle-attribute: preferred_username



#logging:
#  file:
#    path: .
#    name: my_log.txt
